/* Automatically generated by './build/bin/build-entry.js' */

import alert from "src/components/alert/index.js"
import button from "src/components/button/index.js"

const components = [
  alert,
  button
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$YXB = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  alert,
  button
};
